const data = {
	datas: [
		{
			time: "12:10 AM",
			bus_name: "KSRTC Delux",
			from: "Trivandrum",
			to: "Kozhikode",
			available_seats: "52",
			rate: "125",
		},
		{
			time: "01:20 AM",
			bus_name: "CERA",
			from: "Kottayam",
			to: "Kannur",
			available_seats: "60",
			rate: "170",
		},
		{
			time: "02:00 AM",
			bus_name: "KSRTC KSwift",
			from: "Trivandrum",
			to: "Palakkad",
			available_seats: "65",
			rate: "180",
		},
		{
			time: "02:45 AM",
			bus_name: "KSRTC SuperFast",
			from: "Ernakulam",
			to: "Trissur",
			available_seats: "52",
			rate: "",
		},
		{
			time: "03:00 AM",
			bus_name: "KSRTC Garuda",
			from: "Trivandrum",
			to: "Banglore",
			available_seats: "72",
			rate: "03:40",
		},
		{
			time: "06:00 AM",
			bus_name: "KSRTC Minnal",
			from: "Trivandrum",
			to: "Kasargod",
			available_seats: "52",
			rate: "200",
		},
		{
			time: "08:30 AM",
			bus_name: "KSRTC SuperFast",
			from: "Ernakulam",
			to: "Malappuram",
			available_seats: "52",
			rate: "180",
		},
		{
			time: "09:10 AM",
			bus_name: "KSRTC Lowfloor",
			from: "Ernakulam",
			to: "Kozhikode",
			available_seats: "58",
			rate: "200",
		},
		{
			time: "10:15 AM",
			bus_name: "KSRTC SuperFast",
			from: "Trissur",
			to: "Munnar",
			available_seats: "52",
			rate: "150",
		},
		{
			time: "11:30 AM",
			bus_name: "Kallada",
			from: "Trivandrum",
			to: "Banglore",
			available_seats: "68",
			rate: "170",
		},
	],
};

module.exports = data;
